import type { SVGProps } from 'react';
import ActivitySvg from '@material-design-icons/svg/outlined/monitor_heart.svg?raw';
import AppleSvg from '@material-design-icons/svg/outlined/restaurant.svg?raw';
import ArrowLeftSvg from '@material-design-icons/svg/outlined/arrow_back.svg?raw';
import BookOpenSvg from '@material-design-icons/svg/outlined/menu_book.svg?raw';
import CameraSvg from '@material-design-icons/svg/outlined/photo_camera.svg?raw';
import CalendarDaysSvg from '@material-design-icons/svg/outlined/calendar_month.svg?raw';
import CheckSvg from '@material-design-icons/svg/outlined/check.svg?raw';
import ChevronDownSvg from '@material-design-icons/svg/outlined/expand_more.svg?raw';
import ChevronLeftSvg from '@material-design-icons/svg/outlined/chevron_left.svg?raw';
import ChevronRightSvg from '@material-design-icons/svg/outlined/chevron_right.svg?raw';
import CirclePauseSvg from '@material-design-icons/svg/outlined/pause_circle.svg?raw';
import CirclePlaySvg from '@material-design-icons/svg/outlined/play_circle.svg?raw';
import DumbbellSvg from '@material-design-icons/svg/outlined/fitness_center.svg?raw';
import ExternalLinkSvg from '@material-design-icons/svg/outlined/open_in_new.svg?raw';
import FlameSvg from '@material-design-icons/svg/outlined/local_fire_department.svg?raw';
import HeartPulseSvg from '@material-design-icons/svg/outlined/monitor_heart.svg?raw';
import HomeSvg from '@material-design-icons/svg/outlined/home.svg?raw';
import CircleHelpSvg from '@material-design-icons/svg/outlined/help_outline.svg?raw';
import LoaderCircleSvg from '@material-design-icons/svg/outlined/sync.svg?raw';
import MoonSvg from '@material-design-icons/svg/outlined/dark_mode.svg?raw';
import MinusSvg from '@material-design-icons/svg/outlined/remove.svg?raw';
import PencilSvg from '@material-design-icons/svg/outlined/edit.svg?raw';
import PlusSvg from '@material-design-icons/svg/outlined/add.svg?raw';
import RotateCcwSvg from '@material-design-icons/svg/outlined/restart_alt.svg?raw';
import SaveSvg from '@material-design-icons/svg/outlined/save.svg?raw';
import ScaleSvg from '@material-design-icons/svg/outlined/monitor_weight.svg?raw';
import SettingsSvg from '@material-design-icons/svg/outlined/settings.svg?raw';
import SparklesSvg from '@material-design-icons/svg/outlined/auto_awesome.svg?raw';
import SunSvg from '@material-design-icons/svg/outlined/light_mode.svg?raw';
import TimerResetSvg from '@material-design-icons/svg/outlined/timer.svg?raw';
import Trash2Svg from '@material-design-icons/svg/outlined/delete_outline.svg?raw';
import TrendingDownSvg from '@material-design-icons/svg/outlined/trending_down.svg?raw';
import UtensilsSvg from '@material-design-icons/svg/outlined/restaurant.svg?raw';
import WavesSvg from '@material-design-icons/svg/outlined/water.svg?raw';
import XSvg from '@material-design-icons/svg/outlined/close.svg?raw';
import Maximize2Svg from '@material-design-icons/svg/outlined/fullscreen.svg?raw';
import GripVerticalSvg from '@material-design-icons/svg/outlined/drag_indicator.svg?raw';
import StarSvg from '@material-design-icons/svg/outlined/star.svg?raw';
import StarOutlineSvg from '@material-design-icons/svg/outlined/star_border.svg?raw';
import ImageIconSvg from '@material-design-icons/svg/outlined/image.svg?raw';

import BarcodeSvg from '@material-design-icons/svg/outlined/qr_code_scanner.svg?raw';
export const Barcode = material(BarcodeSvg);

type IconProps = SVGProps<SVGSVGElement> & { size?: number | string };
function material(source: string) {
  const markup = source.replace(/<svg[^>]*>/, '').replace('</svg>', '');
  return function MaterialIcon({size = 24, ...props}: IconProps) {
    return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" focusable="false" {...props} dangerouslySetInnerHTML={{__html: markup}} />;
  };
}
export const Activity = material(ActivitySvg);
export const Apple = material(AppleSvg);
export const ArrowLeft = material(ArrowLeftSvg);
export const BookOpen = material(BookOpenSvg);
export const Camera = material(CameraSvg);
export const CalendarDays = material(CalendarDaysSvg);
export const Check = material(CheckSvg);
export const ChevronDown = material(ChevronDownSvg);
export const ChevronLeft = material(ChevronLeftSvg);
export const ChevronRight = material(ChevronRightSvg);
export const CirclePause = material(CirclePauseSvg);
export const CirclePlay = material(CirclePlaySvg);
export const Dumbbell = material(DumbbellSvg);
export const ExternalLink = material(ExternalLinkSvg);
export const Flame = material(FlameSvg);
export const HeartPulse = material(HeartPulseSvg);
export const Home = material(HomeSvg);
export const CircleHelp = material(CircleHelpSvg);
export const LoaderCircle = material(LoaderCircleSvg);
export const Moon = material(MoonSvg);
export const Minus = material(MinusSvg);
export const Pencil = material(PencilSvg);
export const Plus = material(PlusSvg);
export const RotateCcw = material(RotateCcwSvg);
export const Save = material(SaveSvg);
export const Scale = material(ScaleSvg);
export const Settings = material(SettingsSvg);
export const Sparkles = material(SparklesSvg);
export const Sun = material(SunSvg);
export const TimerReset = material(TimerResetSvg);
export const Trash2 = material(Trash2Svg);
export const TrendingDown = material(TrendingDownSvg);
export const Utensils = material(UtensilsSvg);
export const Waves = material(WavesSvg);
export const X = material(XSvg);
export const Maximize2 = material(Maximize2Svg);
export const GripVertical = material(GripVerticalSvg);
export const Star = material(StarSvg);
export const StarOutline = material(StarOutlineSvg);
export const ImageIcon = material(ImageIconSvg);
